### ISSUE TITLE
update方法是不是写的有问题啊

### ISSUE THREAD

**Issue by ZyqGit8** [runzhenghengbin/SpringBoot#3]
update这个方法不应该是先根据id查询到一个girl对象，然后再进行update吗？

**Comment by runzhenghengbin** [comment]
这里只是简单的demo。当然可以先查询下判断是否存在再进行修改



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 朱永奇 <notifications@github.com&gt;
发送时间: 2020年10月26日 11:06
收件人: runzhenghengbin/SpringBoot <SpringBoot@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[runzhenghengbin/SpringBoot] update方法是不是写的有问题啊 (#3)





 
update这个方法不应该是先根据id查询到一个girl对象，然后再进行update吗？

**Comment by runzhenghengbin** [comment]
这里只是简单的demo。当然可以先查询下判断是否存在再进行修改
